Allow checking if dependencies of an application use a forbidden license
datawire/go-mkopensource pull request #14
Opened 2022-01-26 14:43 UTC by aosoriodw

This PR implements validations based on this [document](https://www.notion.so/datawire/License-Management-5194ca50c9684ff4b301143806c92157)

There is a command line option `--application-type` that can be:
`external`: For applications that run on customer servers
`internal`: For applications that run on Ambassador servers

These flags control what validation is applied when checking licenses.

License validation feature has been implemented as a package that can be reused in other applications.

2022-01-26 16:37 UTC, AidanWenzel commented on README.md
> +- Internal: Applies validation for applications that run on customer infrastructure
Should add ` ` around the values - and make sure they match expected string case

2022-01-26 19:01 UTC, AidanWenzel requested changes
Will do another review into the actual code from IDE :+1:

2022-01-26 19:08 UTC, aosoriodw commented on README.md
> +- Internal: Applies validation for applications that run on customer infrastructure
Good catch. I made it consistent with other parameters.

2022-01-28 21:23 UTC, rhs approved these changes

2022-02-02 23:28 UTC, AidanWenzel approved these changes

2022-02-03 01:34 UTC, merged